### ISSUE TITLE
Fix TRUE/FALSE macro colission via prefixing them.

### ISSUE THREAD

**Issue by Khhs167** [Khhs167/memstack#13]
As mentioned in #6, the boolean macros might interfere with user-defined macros, and thus I believe they should be renamed.

My solution would be to rename them to `MSTRUE` and `MSFALSE`, and I'll be opening a PR shortly implementing that.

**Comment by mr-cheffy** [comment]
one question, why is it `1==1` instead of just `1`?

**Comment by Khhs167** [comment]
I don't know, I didn't implement it, so you'll have to ask hrszpuk 'bout that.

**Comment by mr-cheffy** [comment]
he blocked me on discord lol

**Comment by Khhs167** [comment]
@hrszpuk, sorry for the ping. Could you come over here and answer the question about `(1 == 1)` being the value of the TRUE macro?

**Comment by hrszpuk** [comment]
Code for the TRUE/FALSE macros were taken from your issue https://github.com/Khhs167/memstack/issues/7. It is a bit strange but I believe that’s what you wanted for the PR to pass.

**Comment by Khhs167** [comment]
I must've read it somewhere then, don't really know.

**Comment by Khhs167** [comment]
Anyhow, if discussion wants to continue, we'll have to do that somewhere else.

This issue is resolved in #14, so I'll be closing it now!
