### ISSUE TITLE
mspush example segfaults

### ISSUE THREAD

**Issue by Khhs167** [Khhs167/memstack#16]
Transferring from #12

> Unrelated but, when I run make runall I get a segfault on the mspop test.
> ![image](https://github.com/Khhs167/memstack/assets/34920681/f87d3c90-94de-468e-8c7b-f5ae9ebfe89c)
> This doesn't occur using make mspop.run.
> Any idea what could be causing this?

I have been doing some research and the culprit seems to be mspush.

Doing further investigation and looking for a fix rn!

**Comment by mr-cheffy** [comment]
It looks like it segfaults at:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7fb962f in mspush (storage=0x5555555596b0, ptr=0x5555555596d0)
    at src/memstack.c:172
172             storage->last->next = new_node;
```

and storage->last is null meaning you are trying to access a null pointer:

![image](https://github.com/Khhs167/memstack/assets/91018726/098f2d65-b1fe-4ce9-be09-46ac9109eca1)

It's probably being a null pointer because of:

https://github.com/Khhs167/memstack/blob/master/src/memstack.c#L39-L43

**Comment by mauro-balades** [comment]
https://github.com/Khhs167/memstack/blob/master/src/memstack.c#L39-L43

**Comment by Khhs167** [comment]
Issue resolved in https://github.com/Khhs167/memstack/commit/25d95506c8bb0b9db490185555be0c8da51d9352

**Comment by hrszpuk** [comment]
You've named the test `mspop` not `mspush` and it still segfaults because of the null pointer mentioned above.

![image](https://github.com/Khhs167/memstack/assets/107559570/c8cefb81-8b55-4d23-a9d7-236a5b59d00d)

**Comment by hrszpuk** [comment]
Maybe a check should be added to see if `storage->last` is NULL and if so just set `new_node` to `storage->last`?

**Comment by Khhs167** [comment]
I did just that over here
https://github.com/Khhs167/memstack/blob/e6e0adf34a4ac0e606a04a8a9e3da81aea4ec13b/src/memstack.c#L177

**Comment by hrszpuk** [comment]
Even after pull it still segfaults on my machine. Perhaps it's because `new_node->previous = storage->last`? This means after an `mspush` storage->last->previous will be NULL?

**Comment by hrszpuk** [comment]
I'll take a better look in a sec I'm currently debugging from the loo lmao

**Comment by hrszpuk** [comment]
```c
        // TODO: Check if this needs to be done elsewhere
        if(storage->first != NULL) {
        	storage->last->next = new_node;
                new_node->previous = storage->last; // <-- Added this line
        	storage->last = new_node;

        } else {
        	storage->first = new_node;
        	storage->last = storage->first;
        }
```
This seemed to fix it for me @Khhs167!
![image](https://github.com/Khhs167/memstack/assets/107559570/580ca824-bf2a-43dc-8338-91658723bd14)

**Comment by hrszpuk** [comment]
Do test it on your own machines to be sure :P

**Comment by Khhs167** [comment]
Works for me.

We really should get these examples converted into tests lol

**Comment by hrszpuk** [comment]
Yeah haha
