### ISSUE TITLE
1.3.0 Roadmap thing

### ISSUE THREAD

**Issue by Khhs167** [Khhs167/memstack#20]
So, there's been a lot of activity here lately, and I believe we're good underway for 1.3.0 or 1.2.1.

I'll be accepting requests/discussion for when and if we should do a new release.

Current PRs that should be going into 1.2.1(if any major features happen to pop up, 1.3.0):
- #25
- #21
- #19
- #11 (New msprint stuff)
- #27
- #22

**Comment by Khhs167** [comment]
one sec

**Comment by hrszpuk** [comment]
The library fulfills the original project scope. Not sure if we really need anymore features. Keeping the library up to date and bug-free is fine. Otherwise if you really want to improve it, perhaps a logging facility?

**Comment by hrszpuk** [comment]
1.2.1 is probably a better version (for now at least) given it's mostly been bug fixes which makes it more of a "patch" than a "minor" update.

**Comment by Khhs167** [comment]
Nah, I felt more like, any features that still seem like they fit that we need?

There are a couple fixes and tweaks that are ongoing/changed(https://github.com/Khhs167/memstack/tree/msgetelements, #21, etc).

I don't know how to label the release(major or minor?) and how long we should wait for the next release.

Also just general questions if there's any functionality people would like to see

**Comment by Khhs167** [comment]
I've also been thinking about maybe adopting a versioning schema?

More specifically, this one: https://openability.tech/OA_VERSIONING.TXT

**Comment by hrszpuk** [comment]
Ah, the one I'm used to is MAJOR.MINOR.PATCH, but we could use that one if you want.

**Comment by Khhs167** [comment]
MAJOR.MINOR.PATCH being SemVer?

They're pretty much the same

**Comment by hrszpuk** [comment]
> Nah, I felt more like, any features that still seem like they fit that we need?
> 
> There are a couple fixes and tweaks that are ongoing/changed(https://github.com/Khhs167/memstack/tree/msgetelements, #21, etc).
> 
> I don't know how to label the release(major or minor?) and how long we should wait for the next release.
> 
> Also just general questions if there's any functionality people would like to see

We could swap out the backend to be list-based? It would yield better space complexity compared to a linked list.

**Comment by Khhs167** [comment]
Migrated versioning stuff to #22

**Comment by Khhs167** [comment]
> > Nah, I felt more like, any features that still seem like they fit that we need?
> > There are a couple fixes and tweaks that are ongoing/changed(https://github.com/Khhs167/memstack/tree/msgetelements, #21, etc).
> > I don't know how to label the release(major or minor?) and how long we should wait for the next release.
> > Also just general questions if there's any functionality people would like to see
> 
> We could swap out the backend to be list-based? It would yield better space complexity compared to a linked list.

It could be done, I haven't had much experience with array-lists(I suppose that's your idea?), so when I did the original implementation I went for linked lists.

As long as performance doesn't decrease(it should increase) and it stays *relatively* simple, I am more than open to the idea!

**Comment by hrszpuk** [comment]
We don't necessarily have to *replace* the current implementation, just have an additional one that can be used as an alternative.

**Comment by Khhs167** [comment]
I'm going to be headed for a couple hours, and you've got collaborator access, if you want to do it, do it. Just make sure it is on a seperate branch and you follow the proper PR scheme(which I ignored a lot today for quick fixes), and we'll be fine.

If you don't want to implement it because it's a lot of work and you don't want to do it all only to throw it away, that's also fine.

Just expect me to not respond for a couple hours :)

**Comment by hrszpuk** [comment]
That's fine. Thanks for the heads up. I'm gonna be busy anyway :).

**Comment by Khhs167** [comment]
I added a list of current PRs that would come in the next release

**Comment by Khhs167** [comment]
Hopefully everything should now be in the milestone!
https://github.com/Khhs167/memstack/milestone/1

**Comment by Khhs167** [comment]
Added #27 to the list

**Comment by Khhs167** [comment]
I will run the 1.3.0 tests and then release
