### ISSUE TITLE
Adoption of a versioning schema?

### ISSUE THREAD

**Issue by Khhs167** [Khhs167/memstack#22]
I have been wondering about adopting some sort of versioning schema for memstack.

There are a couple options I know of right now:
- https://openability.tech/OA_VERSIONING.TXT (written by me :sunglasses:)
- https://semver.org/

But I am open to other versioning schemas, as well as just ignoring them alltogether.

Opinions and discussions are welcome!

**Comment by mr-cheffy** [comment]
`#define malloc msalloc`

**Comment by Khhs167** [comment]
Uhm, what?

**Comment by mr-cheffy** [comment]
there could be like c's stdlib replacement with memstack's one if `MEMSTACK_REPLACE_CSTDLIB` is enabled

**Comment by Khhs167** [comment]
#20 not here lol.

**Comment by mr-cheffy** [comment]
Lol, sry. Maybe try to enable discussions

**Comment by hrszpuk** [comment]
> - https://openability.tech/OA_VERSIONING.TXT (written by me sunglasses)

This was an interesting read, but some of it is ambiguous and confusing.

> - https://semver.org/

This would be preferable as its a well known and commonly followed type of versioning.

**Comment by hrszpuk** [comment]
> Lol, sry. Maybe try to enable discussions

If people are feeling the need to hijack issues to discuss ideas and potential enhancements for the project then I think discussions would be a good idea.

**Comment by Khhs167** [comment]
> > * https://openability.tech/OA_VERSIONING.TXT (written by me sunglasses)
> 
> This was an interesting read, but some of it is ambiguous and confusing.
> 
> > * https://semver.org/
> 
> This would be preferable as its a well known and commonly followed type of versioning.

I feel like SemVer might be the better option, if that's the more well known one.

As of right now, pushing a release would force us to go with 1.3.0 no matter what schema we use, since both SemVer and the OA schema, state that the patch/subminor number is for bug fixes, not for API changes. And we've introduced new API with a couple of the new PRs.

I'm fine with both, so I feel like it is up to your preference.

**Comment by mr-cheffy** [comment]
This is being extremely overengeniered. Just use a standardized version like SemVer.

**Comment by Khhs167** [comment]
I'd like to close this issue for once. I'm fine with SemVer, just want global approval.

1.3.0 has been in the oven for over half a year by now, and should be able to be the final release.

**Comment by mr-cheffy** [comment]
Close it then

**Comment by Khhs167** [comment]
I just want to get verbal confirmation from everyone that we're going SemVer :)

pinging @hrszpuk to get his attention, since he counts as a maintainer too

**Comment by hrszpuk** [comment]
Yeah just pull the trigger

**Comment by Khhs167** [comment]
Aight, it's official.
Any future versions will now be using SemVer :)

**Comment by mr-cheffy** [comment]
bro really took 1 year to decide what versioning scheme he wanted to use
