### ISSUE TITLE
Figure out the msgetelements branch

### ISSUE THREAD

**Issue by Khhs167** [Khhs167/memstack#26]
The [msgetelements](https://github.com/Khhs167/memstack/tree/msgetelements) branch is currently way behind main, and introduces a new feature, but I don't know whether or not it is a feature that belongs.

Any ideas?

**Comment by hrszpuk** [comment]
If we add a list-based or even array-based memstack it would become redundant. I can't think of any cases where I might use it tbh.

**Comment by Khhs167** [comment]
I'll be leaving the branch there, closing this issue, and if anyone feels like doing something with it, they can do so.

Okay?
