### ISSUE TITLE
msinit() does not ensure global is not already allocated.

### ISSUE THREAD

**Issue by hrszpuk** [Khhs167/memstack#3]
### "global" could already be allocated with memory
Global is uninitalised, and becomes initalised after `msinit()`. However, `msinit()` does not ensure global does not already have memory allocated to it (likely by another `msinit()` call).
```c
memstack* global;

void msinit(){
    // You don't check if global is NULL O_O
    global = msnew();
}
```
This causes issues as memory is not freed. `msinit()` could be called twice and the previous allocation would be overwritten.

### Solution
This ensures global is correctly freed before being re-allocated.
```c
memstack* global = NULL;

void msinit(){
    if (global != NULL) {
        global = msnew();
    } else {
        msfree(global);
        global = msnew();
    } 
}
```

**Comment by Khhs167** [comment]
Fixed in https://github.com/Khhs167/memstack/pull/4
