### ISSUE TITLE
TRUE Macro, yay or nay?

### ISSUE THREAD

**Issue by Khhs167** [Khhs167/memstack#7]
Simple as that, should the library have a TRUE macro?
```c
#define TRUE (1==1)
#define FALSE (!TRUE)
```
Let me know.

**Comment by Khhs167** [comment]
#6

**Comment by hrszpuk** [comment]
I made a [comment](https://github.com/Khhs167/memstack/pull/6#issuecomment-1211397646) that the macro could conflict with user defined macros or macros define in other libraries in #6. However, you make a good point: when are TRUE and FALSE defined differently from 0 and 1? I'm fine either way, I'm about to leave to go on holiday so it's your call boss.

**Comment by hrszpuk** [comment]
This issue can now be closed, the macros have been added in #9.

**Comment by Khhs167** [comment]
closing after some time lol

**Comment by hrszpuk** [comment]
This project is pretty much completed - I don't think there is anything else to really add.
